# Generated by Django 3.2.10 on 2022-07-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
