# Generated by Django 3.2.10 on 2022-07-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0004_rename_account_useraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='Account',
        ),
    ]
