# Generated by Django 3.2.10 on 2022-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0007_auto_20220716_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
